sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
before_install:
- gem install bundler
- bundle install
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
notifications:
  email: false
env:
  global:
    secure: CBI+2WSAlg+MijEc5o3hKW6svE659sM2LiuC9LqtXOH17iRNS0uENBZyuzcI+sCYtHzb+wJuTYtQX8RsUsaB2tl3CWOJBtazDWwNUUyhS4PgRCK36nRXdaXSA1tQ24zK6Z9/MbgJ+YYReW/9zNSvwFjy1sxLCHTAtKTzbBTmaAWHgoG/bLzw8Rl4tPFdI3UZwQGzEvbJLjE/9F6kS0X8Hm49UmmzvkQ6FI7kS16WT1cW3Kybnnx1Nd+HbzQe40cFz6vjjEuVwCcS0hNmpVyzU/PGXO8Y0am/BhdHcpiV4CCDzdARkwwjYMSM2MBSt8XzuPn75sFvmQjawChcD2zwbKXYpjo74XWhqoKwfzJrZTJiPGcTcA3acEhgr80RURdgCG4bzmhrOHYZdZ42KDDJAVNLPnICeHe5fXtAe5/AJUIFdEmRkQZLhNc8MWB9gFvaXFglm/D9shuQABM1zODNNr03AU0Hnw1hgy/WKyO0tAKlZsqWaanBV9QLbSgDzWUWYjXoNN3WT8ESLjMrebUlkA9xhNzURbsOKEgS9RJW3D6KZ249IaPojxay3o3kAbSV7G87isnQnBU411Z5N2jLveB+/+PE/jHYN2NuZ+xoUIMv/eoeUTH9rGS0lWhZ+CjK+U83jYLad9Fm0a0A7KiKjpML4sslufyCjaG4W/wATtQ=
